version: "3.5"

services:
#  nginx-kbase:
#    image: nginx:1.21.6
#    container_name: nginx-kbase
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#    depends_on:
#      - know-base-service
#    networks:
#      kbase-net:
#        ipv4_address: 172.28.1.1

  postgres-kbase:
    image: postgres:14
    container_name: postgres-kbase
    restart: unless-stopped
    environment:
      POSTGRES_DB: kbase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./docker-volumes/postgres-kbase-data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      kbase-net:
        ipv4_address: 172.28.1.2

  redis-kbase:
    image: redis:7.0
    container_name: redis-kbase
    restart: unless-stopped
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis:/usr/local/etc/redis
      - ./docker-volumes/redis-kbase-data:/data
    ports:
      - ${REDIS_PORT}:6379
    networks:
      kbase-net:
        ipv4_address: 172.28.1.3

  know-base-service:
    build: know-base-service
    container_name: know-base-service
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres-kbase
      - redis-kbase
    ports:
      - "8080:8080"
    networks:
      kbase-net:
        ipv4_address: 172.28.1.4
networks:
  kbase-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
