debug: ${SPRING_DEBUG:false}
server:
  port: ${APP_PORT:9000}
  forward-headers-strategy: framework

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 25
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 120000
    url: ${POSTGRES_URL}?currentSchema=${POSTGRES_SCHEMA:kbase}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  application:
    name: kbase
  jpa:
    show-sql: ${SPRING_DEBUG:true}
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml
    default-schema: ${POSTGRES_SCHEMA:kbase}

cache:
  user-maximum-size: 100000
  user-expired-time-hours: 4

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full

app:
  url: ${APP_URL}
  api-path: ${API_PATH:/}
  jwt-signing-key: ${JWT_SIGNING_KEY}
  token-ttl: ${TOKEN_TTL:4}
